### ISSUE TITLE
Publish this page on github?

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/UVviewsoft_homepage#12]
@d-mal @ildarkhasanshin 
I wanted to move CudaText webpages to Github.io, to make page like cudatext.github.io. But not figured out how to post my html pages. Maybe you can help?
To make such a page and give me the login.
maybe another free/opensource hosting can be used.

**Comment by ildarkhasanshin** [comment]
https://cudatext.github.io/
old?

**Comment by Alexey-T** [comment]
that was my attempt, yes it is old, and it is not so good as current Cud homepage. no scroller-of-pics, not nice header, Github's header is of blue color- not ok.

**Comment by ildarkhasanshin** [comment]
github pages / github.io поддерживает html
сейчас на cudatext.github.io выводится контент из index.md
поэтому нужно удалить index.md и папку img 
потом выгрузить все с https://github.com/Alexey-T/UVviewsoft_homepage/tree/master/cudatext в эту репу

**Comment by Alexey-T** [comment]
спасибо, попробую так сделать.
